### ISSUE TITLE
Memory leak in GenericValue

### ISSUE THREAD

**Issue by huangyihe** [huangyihe/llvm-3.6.0#1]
Because C++ doesn't allow us to use std::unique_ptr in unions (GenericValues), there are actually memory leaks all over the place right now. We need to fix it at some point.

**Comment by huangyihe** [comment]
Memory is leaking every time when we access a floating point number... Blame the RealLib copy constructor for it...

**Comment by hblumberg** [comment]
Fixed except for when a value is re-inserted into the SmartFloatMap!

**Comment by danking** [comment]
@huangyihe Just fixed this problem.

**Comment by danking** [comment]
@huangyihe fixed this in commit c151f30
