### ISSUE TITLE
Various unhandled instructions in `lib/ExecutionEngine/Interpreter/Execution.cpp`

### ISSUE THREAD

**Issue by danking** [huangyihe/llvm-3.6.0#14]
We need to ensure that SmartFloat is propagated appropriately.

This could cause segmentation faults (segfaults).

**Comment by huangyihe** [comment]
Fixed all conversions to/from/between floating point number. Floating point comparison still doesn't work.

**Comment by danking** [comment]
I'll open a new issue for floating point comparison.
