### ISSUE TITLE
How should we handle external function calls that aren't `cmath`?

### ISSUE THREAD

**Issue by danking** [huangyihe/llvm-3.6.0#16]
Not sure. We have to get the FFI thing working so that it can use an ABI to call directly to a binary.

If we call into a binary what do we do about Floats? We can assume the library is correct and that the returned float is completely accurate.

We could also compute an error of the output based on a function of the input errors.

**Comment by huangyihe** [comment]
FFI working now. I'll open a new issue about the input/output thing.
