### ISSUE TITLE
Error when making test cases

### ISSUE THREAD

**Issue by paolamariselli** [huangyihe/llvm-3.6.0#20]
When running:
../llvm-3.6.0/build/bin/lli -force-interpreter test-case2-pow.bc [or any other test case]

Obtain error:
LLVM ERROR: Could not resolve external global address: __dso_handle

**Comment by huangyihe** [comment]
Something in the standard library is causing a dynamically linked function being called, which isn't handled right now. It should be fixed after we make the LibFFI stuff work.

**Comment by huangyihe** [comment]
Okay I see... Do not using anything from `<iostream>` or `<iomanip>` and it should work... As far as I can tell `printf` works fine.

**Comment by huangyihe** [comment]
The `-fno-use-cxa-atexit` compiler flag fixes it in most cases.
