### ISSUE TITLE
More informative error reporting

### ISSUE THREAD

**Issue by huangyihe** [huangyihe/llvm-3.6.0#27]
Interesting source http://llvm.org/docs/SourceLevelDebugging.html#ccxx-frontend

**Comment by danking** [comment]
@hblumberg Is gonna add line numbers to resolve this issue.

**Comment by hblumberg** [comment]
Done in commit 98a736278e91135b628f34a25443d39a04a9fc5b!

**Comment by huangyihe** [comment]
:thumbsup:
