### ISSUE TITLE
Unwanted "precision loss" message

### ISSUE THREAD

**Issue by hblumberg** [huangyihe/llvm-3.6.0#28]
Sometimes the following line
std::cerr << "Precision loss at " << #OP << std::endl;        \

prints the following message
Precision loss at <

when run on polygon.c

![screen shot 2015-05-06 at 6 52 06 pm](https://cloud.githubusercontent.com/assets/8495791/7505617/af1e323a-f422-11e4-848e-d8f16c64d666.png)

Sometimes it takes a couple tries to replicate the bug!

**Comment by hblumberg** [comment]
@huangyihe

**Comment by huangyihe** [comment]
This actually means that the "<" operator returned different results between floating point and real number semantics!

**Comment by hblumberg** [comment]
Sorry, misunderstood this! (:
