### ISSUE TITLE
Array of Floats - Assert Failure

### ISSUE THREAD

**Issue by hblumberg** [huangyihe/llvm-3.6.0#3]
The following assert in LoadRealValueFromMemory fails when dealing with arrays of floats:
assert(result->second->GetExtFloatTy() == FloatTy);

(For example, using float xs[5] = {1000000, 0.01, 0.01, 0.01, 0.01); in our toy example.)

**Comment by huangyihe** [comment]
I can't reproduce this problem right now... Can anybody verify that it's somehow fixed already?

**Comment by danking** [comment]
Can't reproduce this, WONTFIX
