### ISSUE TITLE
Implement cmath functions

### ISSUE THREAD

**Issue by danking** [huangyihe/llvm-3.6.0#4]
- [x] cos
 - [x] sin
 - [x] tan
 - [x] acos
 - [x] asin
 - [x] atan
 - [x] atan2
 - [x] cosh
 - [x] sinh
 - [x] tanh
 - [x] acosh
 - [x] asinh
 - [x] atanh
 - [x] exp
 - [x] frexp
 - [x] ldexp
 - [x] log
 - [x] log10
 - [x] modf
 - [x] exp2
 - [x] expm1
 - [x] ilogb
 - [x] log1p
 - [x] log2
 - [x] logb
 - [x] scalbn
 - [x] scalbln
 - [x] pow
 - [x] sqrt
 - [x] cbrt
 - [x] hypot
 - [x] erf
 - [x] erfc
 - [x] tgamma
 - [x] lgamma
 - [x] ceil
 - [x] floor
 - [x] fmod
 - [x] trunc
 - [x] round
 - [x] lround
 - [x] llround
 - [x] rint
 - [x] lrint
 - [x] llrint
 - [x] nearbyint
 - [x] remainder
 - [x] remquo
 - [x] copysign
 - [x] nan
 - [x] nextafter
 - [x] nexttoward
 - [x] fdim
 - [x] fmax
 - [x] fmin
 - [x] fabs
 - [x] abs
 - [x] fma

**Comment by danking** [comment]
Fixed all of these.

**Comment by huangyihe** [comment]
Hi Dan did you push the commit? I still only have `pow()` right now...

**Comment by danking** [comment]
Nice catch @huangyihe , I just pushed commit d135a5c that fixes this.
